package viagens;

import p185296_m203380.ft.unicamp.trip_helper.R;

public class Viagens {

    public static Viagem[] viagens = {
            new Viagem("Campinas", R.drawable.campinas,"Campinas é um município brasileiro no interior do estado de São Paulo, Região Sudeste do país. Pertence à microrregião e mesorregião homônimas, distante 99 km a noroeste de São Paulo, capital estadual. Ocupa uma área de 797,6 km², da qual 238,323 km² estão em perímetro urbano e os 559,277 km² restantes constituem a zona rural. Em 2018, sua população foi estimada pelo Instituto Brasileiro de Geografia e Estatística em 1 194 094 habitantes, sendo o terceiro município mais populoso de São Paulo (ficando atrás de Guarulhos e da capital) e o décimo quarto de todo o país.", "Brasil"),
            new Viagem("São Paulo", R.drawable.saopaulo,"São Paulo é um município brasileiro, capital do estado homônimo e principal centro financeiro, corporativo e mercantil da América do Sul. É a cidade mais populosa do Brasil, do continente americano, da lusofonia e de todo o hemisfério sul. São Paulo é a cidade brasileira mais influente no cenário global, sendo, em 2016, a 11.ª cidade mais globalizada do planeta, recebendo a classificação de cidade global alfa, por parte do Globalization and World Cities Study Group & Network (GaWC).", "Brasil"),
            new Viagem("Rio de Janeiro", R.drawable.riojaneiro, "Rio de Janeiro (frequentemente referida simplesmente como Rio) é um município brasileiro, capital do estado homônimo, situado no Sudeste do país. Maior destino turístico internacional no Brasil, da América Latina e de todo o Hemisfério Sul, a capital fluminense é a cidade brasileira mais conhecida no exterior, funcionando como um \"espelho\", ou \"retrato\" nacional, seja positiva ou negativamente. É a segunda maior metrópole do Brasil (depois de São Paulo), a sexta maior da América e a trigésima quinta do mundo. Sua população estimada pelo IBGE para 1.º de julho de 2018 era de 6 688 927 habitantes.", "Brasil"),
            new Viagem("Santiago", R.drawable.santiago, "Santiago, por vezes chamada Santiago do Chile para a distinguir de cidades homónimas, é a capital e a maior cidade do Chile. Está localizada na Região Metropolitana de Santiago, no vale central chileno, ao lado da cordilheira dos Andes. É o maior e mais importante e desenvolvido centro urbano, financeiro, cultural e administrativo do país. Chamada de Grande Santiago ou simplesmente Santiago, é uma aglomeração que possui 32 comunas de maneira íntegra e 11 comunas de forma parcial", "Chile"),
            new Viagem("Cidade do Mexico", R.drawable.cidademexico, "A Cidade do México é a capital do México e sede dos poderes federais dos Estados Unidos Mexicanos, constituindo uma de suas 32 entidades federativas, bem como figurando como a maior e mais importante entidade urbana do país. A Cidade do México, com 8 864 370 habitantes (2012), é a cidade mais populosa do México e da América do Norte. Ocupa uma décima parte do Vale do México no centro-sul do país, em um território que se formou da bacia hidrográfica do lago de Texcoco. ", "Mexico"),
            new Viagem("Nova York", R.drawable.novayork, "Nova York ou Nova Iorque é a cidade mais populosa dos Estados Unidos e o centro da Região Metropolitana de Nova York, uma das áreas metropolitanas mais populosas do mundo. É também a terceira cidade mais populosa da América, atrás de São Paulo e Cidade do México. A cidade exerce um impacto significativo sobre o comércio, finanças, mídia, arte, moda, pesquisa, tecnologia, educação e entretenimento de todo o planeta. Nova York abriga a sede da Organização das Nações Unidas (ONU), sendo um importante centro para assuntos internacionais e amplamente considerada como a capital cultural do mundo.", "Estados Unidos"),
            new Viagem("Los Angeles", R.drawable.losangeles, "Los Angeles é a segunda cidade mais populosa dos Estados Unidos (a mais populosa é Nova York). Com uma população de 3 792 621 habitantes, segundo o censo de 2010, é a cidade mais populosa do estado da Califórnia e do oeste dos Estados Unidos. Além disso, a cidade se estende por 1 302 km² no Sul da Califórnia e é classificada como a 16ª maior área metropolitana do mundo. A área metropolitana Los Angeles-Long Beach-Santa Ana abriga 12 828 837 habitantes. Los Angeles é também a sede do condado de Los Angeles, o mais populoso e um dos condados mais multiculturais dos Estados Unidos.", "Estados Unidos"),
            new Viagem("Toronto", R.drawable.toronto, "Toronto é a maior cidade e maior centro financeiro do Canadá, além de capital da província canadense de Ontário. Com uma população estimada de 2.731.571 de habitantes em 2016, é a quarta cidade mais populosa da América do Norte depois da Cidade do México, Nova York e Los Angeles. Toronto é a cidade mais importante da região metropolitana de Toronto, a região metropolitana mais populosa do Canadá, e âncora da Golden Horseshoe, uma região urbanizada em Ontário que abriga cerca de 9,2 milhões de pessoas, ou mais de 26% da população do Canadá. Uma cidade global,Toronto é um centro internacional de negócios, finanças, arte, cultura, qualidade de vida e segurança. ", "Canada"),
            new Viagem("Londres", R.drawable.londres, "Londres  é a capital da Inglaterra e do Reino Unido. Por dois milênios, foi um grande povoado e sua história remonta à sua fundação pelos romanos, quando foi nomeada Londínio. O centro de Londres, a antiga City of London, também conhecida como The Square Mile (\"a milha quadrada\") ou The City, mantém suas fronteiras medievais. Pelo menos desde o século XIX, o nome \"Londres\" se refere à metrópole desenvolvida em torno desse núcleo. Hoje, a maior parte dessa conurbação constitui a região da Grande Londres, cuja área administrativa tem seu próprio prefeito eleito e assembleia.", "Inglaterra"),
            new Viagem("Dublin", R.drawable.dublin, "Dublin ou, em língua portuguesa, Dublim é a capital e maior cidade da Irlanda. O nome em inglês deriva da palavra irlandesa \"Dubhlinn\" (ocasionalmente também grafada Duibhlinn ou Dubh Linn), que significa \"Lago Negro\". Localiza-se na província de Leinster próxima ao ponto mediano da costa leste da Irlanda, sendo cortada pelo Rio Liffey e o centro da região de Dublin. Desde 1898 possui nível administrativo de condado (county-boroughs). Seus limites são os condados de Fingal a norte, Dublin meridional a sudoeste e Dun Laoghaire-Rathdown a sudeste. Tem uma população de 527.612 habitantes na cidade, e sua área metropolitana tem 1.809.156 habitantes.", " Republica da Irlanda"),
            new Viagem("Lisboa", R.drawable.lisboa, "Lisboa é a capital de Portugal e a cidade mais populosa do país. Tem uma população de 506 892 habitantes, dentro dos seus limites administrativos. Na Área Metropolitana de Lisboa, residem 2 821 697 pessoas (2011), sendo por isso a maior e mais populosa área metropolitana do país. Lisboa é o centro político de Portugal, sede do Governo e da residência do chefe de Estado. É o \"farol da lusofonia\" (Daus): a Comunidade dos Países de Língua Portuguesa (CPLP) tem a sua sede na cidade. É ainda a capital mais a ocidente do continente europeu na costa atlântica.", "Portugal"),
            new Viagem("Madrid", R.drawable.madrid, "Madrid ou Madri (apenas em português brasileiro) é a capital e a maior cidade da Espanha. Tem uma população de aproximadamente 3,3 milhões de pessoas, com uma área metropolitana com cerca de 6,5 milhões de habitantes. É a terceira maior cidade da União Europeia (UE), depois de Londres e Berlim, e sua área metropolitana é a terceira maior da UE, depois de Londres e Paris. A área urbana da capital espanhola abrange um total de 604,3 de quilômetros quadrados.", "Espanha"),
            new Viagem("Paris", R.drawable.paris, "Paris  é a capital e a mais populosa cidade da França, bem como a capital da região administrativa de Ilha de França. A cidade se situa em um dos meandros do Sena, no centro da bacia parisiense, entre os confluentes do Marne e do Sena rio acima, e do Oise e do Sena rio abaixo. Como a antiga capital de um império estendido pelos cinco continentes, é, hoje, a capital do mundo francófono.  posição de Paris numa encruzilhada entre os itinerários comerciais terrestres e fluviais no coração de uma rica região agrícola a tornou uma das principais cidades da França ao longo do século X, beneficiada com palácios reais, ricas abadias e uma catedral.", "França"),
            new Viagem("Roma", R.drawable.roma,"Roma é uma cidade e uma comuna especial (chamada \"Roma Capitale\") da Itália. É a capital do país, da província homônima e também da região do Lácio. Com 2,8 milhões de habitantes em 1285,3 km² de área, também é a maior cidade italiana e a quarta cidade mais populosa da União Europeia. A área urbana de Roma se estende além dos limites administrativos da cidade com uma população de cerca de 3,8 milhões. Entre 3,2 e 4,2 milhões de pessoas vivem na área metropolitana da capital italiana. A cidade está localizada na porção centro-ocidental da península itálica, cortada pelo rio Tibre, dentro do Lácio. Roma é a única cidade no mundo que tem em seu interior um país inteiro, o enclave do Vaticano.", "Itália"),
            new Viagem("Berlim", R.drawable.berlim, "Berlim (em alemão Berlin) é a capital e um dos dezesseis estados da Alemanha. Com uma população de 3,5 milhões dentro de limites da cidade, é a maior cidade do país, e a sétima área urbana mais povoada da União Europeia. Situada no nordeste da Alemanha, é o centro da área metropolitana de Berlim-Brandemburgo, que inclui 5 milhões de pessoas de mais de 190 nações. Localizada na grande planície europeia, Berlim é influenciada por um clima temperado sazonal. Cerca de um terço da área da cidade é composta por florestas, parques, jardins, rios e lagos.", "Alemanha"),
            new Viagem("Moscou", R.drawable.moscow, "Moscou é a capital, cidade e subdivisão federal mais populosa da Federação Russa. A cidade é um importante centro político, econômico, cultural, científico, religioso, financeiro, educacional e de transportes da Rússia e do continente. Moscou é a megacidade mais ao norte na Terra, a segunda cidade mais populosa da Europa, atrás de Istambul, e a sexta cidade mais populosa do mundo, ficando atrás somente de Xangai, Istambul, Pequim, Bombaim e Carachi. Sua população, de acordo com os resultados de estatísticas federais, já ultrapassou os 12 milhões. Com base na lista de 2012 da Forbes, Moscou tem a segunda maior comunidade de milionários do mundo.", "Rússia"),
            new Viagem("Cairo", R.drawable.cairo, "Cairo é a capital do Egito e da província homônima. É a maior cidade do mundo árabe e da África. Os egípcios a denominam muitas vezes simplesmente com o nome do país no idioma local, Miṣr (مصر) em árabe clássico e Miṣr em árabe egípcio. Cairo está localizado nas margens e ilhas do rio Nilo, ao sul do delta. Ao sudoeste se encontra Giza e a antiga necrópole de Mênfis, com a meseta de Giza e suas monumentais pirâmides, como a Grande Pirâmide de Quéops. A cidade foi fundada no ano 969 por Jauar, o Siciliano, do califado Fatímida. ", "Egito"),
            new Viagem("Dubai", R.drawable.dubai, "O Emirado de Dubai está localizado na costa do Golfo Pérsico, sendo um dos sete emirados que compõem o país. Dubai é o emirado mais populoso entre os sete emirados, com aproximadamente 2 262 000 habitantes. Está localizada ao longo da costa sul do Golfo Pérsico na Península Arábica na Ásia. O município muitas vezes é chamado de Cidade de Dubai para diferenciá-lo do emirado homônimo. A cidade é conhecida mundialmente por ser extremamente desenvolvida e por seus enormes arranha-céus e largas avenidas.", "Emirados Árabes"),
            new Viagem("Pequim", R.drawable.pequim, "Pequim é a capital da República Popular da China e uma das metrópoles mais populosas do mundo. Em 2013 a população da cidade foi estimada em 20 150 000 habitantes. A cidade, localizada no norte da China, é governada como uma municipalidade diretamente controlada pelo governo nacional, com 14 distritos urbanos e suburbanos e dois condados rurais. O Município de Pequim é cercado pela província de Hebei, com excepção da municipalidade vizinha de Tianjin, ao sudeste. A cidade é a segunda maior do país por população urbana, depois de Xangai, e é o centro político, cultural e educacional do país. É a sede da maioria das maiores empresas estatais chinesas e é um importante polo de rodovias nacionais, vias expressas, ferrovias e redes ferroviárias de alta velocidade. O Aeroporto Internacional de Pequim é o segundo mais movimentado do mundo por tráfego de passageiros.", "China"),
            new Viagem("Nova Deli", R.drawable.novadeli, "Nova Deli, Nova Delhi  ou Nova Déli é a capital da Índia. Com uma área total de 42,7 km², Nova Deli situa-se dentro da metrópole do mesmo nome, e atualmente serve como sede do Governo da Índia, da República da Índia, além do governo do Território da Capital Nacional. Projetada pelo arquiteto britânico Edwin Lutyens, a cidade é conhecida por seus bulevares amplos e cercados por árvores, e por ser sede de diversas instituições e monumentos nacionais.De 1911 até Proclamação da Independência da Índia em 1947,a cidade era a capital e centro administrativo da colônia e desde então manteve esse status.", "Índia"),
            new Viagem("Bangkok", R.drawable.bangkok, "Bangkok ou Bancoque (em português brasileiro) é a capital e cidade mais populosa da Tailândia, além de principal centro financeiro, corporativo, mercantil, cultural e histórico do país. É a décima cidade mais populosa da Ásia e a vigésima quarta mais populosa do mundo. Situada na margem esquerda do rio Chao Phraya, nas proximidades do Golfo da Tailândia, a cidade possui cerca de 8 280 925 habitantes (2011), enquanto a Grande Bangkok reúne 14,6 milhões de habitantes, sendo que aproximadamente 12,6% da população do país vive na sua área metropolitana, ocupando o posto de 30.ª região metropolitana mais populosa do mundo. A cidade ocupa 1 568,7 quilômetros quadrados, no delta do rio Chao Phraya, e está localizada na região Central da Tailândia.", "Tailândia"),
            new Viagem("Tokyo", R.drawable.tokyo, "Tokyo ou Tóquio (português brasileiro), oficialmente Metrópole de Tokyo é a capital do país e de uma das 47 prefeituras do Japão. Situa-se em Honshu, a maior ilha do arquipélago. Em 2015, Tóquio possuía 13 491 000 habitantes, cerca de 11% da população do país, e a Região Metropolitana de Tóquio possui mais de 37 milhões de habitantes, o que torna a aglomeração de Tóquio, independentemente de como se define, como a área urbana mais populosa do mundo. Um de seus monumentos mais famosos é a Torre de Tóquio. Foi fundada em 1457, com o nome de Edo ou Yedo. Tornou-se a capital do Império em 1868 com a atual designação. Tokyo é considerada um dos maiores centros financeiros do mundo ao lado de Nova Iorque e Londres.", "Japão"),
            new Viagem("Seul", R.drawable.seul, "Seul oficialmente Cidade Especial de Seul, é a capital e a maior metrópole da República da Coreia, mais conhecida como Coreia do Sul. A cidade é o núcleo da Região Metropolitana de Seul, que inclui a metrópole vizinha de Incheon e a província de Gyeonggi, a segunda maior área metropolitana do mundo, com mais de 25 milhões de habitantes. Situado às margens do rio Han, a história de Seul remonta a mais de dois mil anos, quando foi fundada em 18 a.C. por Baekje, um dos Três Reinos da Coreia. A cidade continuou como a capital coreana sob a Dinastia Joseon. A região de Seul contém cinco Patrimônios Mundiais da UNESCO: Complexo de Palácios de Ch'angdokkgung, Fortaleza de Hwasong, Santuário de Chongmyo, Namhansanseong e os Túmulos Reais da Dinastia Joseon.", "Coreia do Sul"),
            new Viagem("Sydney", R.drawable.sydney, "Sydney é a capital do estado de Nova Gales do Sul e a cidade mais populosa de toda a Austrália e Oceania. Está localizada na costa sudeste do país, ao longo do mar da Tasmânia e em torno de um dos maiores portos naturais do mundo. Os moradores são conhecidos localmente como sydneysiders e constituem a cidade mais multicultural da Austrália. Desde que transporte de condenados terminou, em meados do século XVIII, a cidade se tornou um centro cultural e econômico global. A população de Sydney no momento do censo de 2011 era de 4,39 milhões de habitantes. Cerca de 1,5 milhão deste total nasceram no exterior e representam uma multiplicidade de diferentes países de todo o mundo. Existem mais de 250 línguas diferentes faladas em Sydney e cerca de um terço dos moradores falam em casa uma língua diferente do inglês.", "Australia"),
    };
}
